name: Publish Plugin Release

on: workflow_dispatch

jobs:
  release:
    runs-on: ubuntu-latest
    env:
      RELEASE_BUILD: true
      MAVEN_TOKEN: ${{ secrets.MAVEN_TOKEN }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Setup JDK 17
        uses: actions/setup-java@v4
        with:
          java-version: '17'
          distribution: temurin
          cache: gradle

      - name: Build & Publish
        run: cd buildSrc && ../gradlew build publish